In [2]:
import pandas as pd
import numpy as np

## Datatypes and Attributes

In [3]:
#numpy's main datatype is ndarray - n dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1, 2, 3],
              [4, 5.0, 6],
              [7.5, 8, 9]])
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [7.5, 8. , 9. ]])

In [28]:
a3 = np.array([[[1, 2, 3],
               [4, 5.0, 6],
               [7.5, 8, 9],],
              [[1.1, 2.8, 3.5],
               [4.7, 5.0, 6.9],
               [7.5, 8.8, 9.9]],
              [[3, 2, 1],
               [6, 5, 4],
               [9, 8, 7]]])
a3

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7.5, 8. , 9. ]],

       [[1.1, 2.8, 3.5],
        [4.7, 5. , 6.9],
        [7.5, 8.8, 9.9]],

       [[3. , 2. , 1. ],
        [6. , 5. , 4. ],
        [9. , 8. , 7. ]]])

In [29]:
a3.shape

(3, 3, 3)

In [18]:
temp = pd.DataFrame(a2)
temp

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.5  8.0  9.0

In [26]:
v = np.array([[[1, 2, 3, 4],
               [4, 5, 6, 7]]])
v

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [27]:
v.shape, a1.shape

((1, 2, 4), (3,))

## Creating Arrays

In [36]:
ones = np.ones([3,3,3])
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
type(ones)

numpy.ndarray

In [40]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
range_array = np.arange(0, 5, 1)
range_array

array([0, 1, 2, 3, 4])

In [50]:
random_array = np.random.randint(0, 10, size = (3,5))
random_array

array([[0, 5, 5, 0, 9],
       [0, 4, 4, 8, 5],
       [5, 2, 7, 5, 1]])

In [56]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.21762205, 0.10242472, 0.21184598],
       [0.42908395, 0.25900326, 0.92227628],
       [0.9036118 , 0.77839836, 0.17876926],
       [0.54084225, 0.00293579, 0.12693123],
       [0.71243743, 0.50037072, 0.87479424]])

In [58]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.38637295, 0.64854829, 0.60368514],
       [0.87865681, 0.65039938, 0.55086829],
       [0.20855907, 0.05656277, 0.66256019],
       [0.33553635, 0.77470533, 0.5973848 ],
       [0.61059477, 0.68311962, 0.28895255]])

## Pseudo Random Numbers

In [69]:
#seed makes the randomization obvious
#random seed helps creates random numbers which donot change 
np.random.seed(0)

random_array_5 = np.random.randint(50, size = (3,3))
random_array_5

array([[44, 47,  0],
       [ 3,  3, 39],
       [ 9, 19, 21]])

In [79]:
np.random.seed(5)
random_array_6 = np.random.random((5,3))
#random_array_6
random_array_6.size

15

In [77]:
#Finding Unique Values
#np.unique(random_array_6)
len(np.unique(random_array_6))

15

## Viewing Arrays and Matrices

In [81]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [7.5, 8. , 9. ]])

In [86]:
a2[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [87]:
a3

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7.5, 8. , 9. ]],

       [[1.1, 2.8, 3.5],
        [4.7, 5. , 6.9],
        [7.5, 8.8, 9.9]],

       [[3. , 2. , 1. ],
        [6. , 5. , 4. ],
        [9. , 8. , 7. ]]])

In [91]:
a3[:3, :2, 1:]

array([[[2. , 3. ],
        [5. , 6. ]],

       [[2.8, 3.5],
        [5. , 6.9]],

       [[2. , 1. ],
        [5. , 4. ]]])

In [103]:
five_dim = np.random.randint(1, 5, (2,1,2,3,3))
five_dim

array([[[[[1, 4, 2],
          [1, 3, 3],
          [2, 4, 1]],

         [[1, 2, 1],
          [2, 2, 1],
          [3, 4, 2]]]],



       [[[[3, 1, 4],
          [2, 4, 3],
          [1, 4, 1]],

         [[1, 2, 1],
          [2, 1, 3],
          [2, 4, 4]]]]])

In [26]:
temp = np.random.randint(1, 5, (2,2,2))
temp

array([[[2, 2],
        [1, 1]],

       [[2, 2],
        [2, 2]]])

In [104]:
five_dim[:, :, :, 1:2,1:2]

array([[[[[3]],

         [[2]]]],



       [[[[4]],

         [[1]]]]])

## Manipulating and Comparing Arrays

<h2>Arithmetic</h2>

In [109]:
ar1 = np.array([1, 2, 3])
ar1

array([1, 2, 3])

In [111]:
ar2 = np.ones((1,3))
ar2

array([[1., 1., 1.]])

In [34]:
ar3 = np.array([[1, 2, 3],
              [4, 2, 3]])

In [112]:
ar1 + ar2

array([[2., 3., 4.]])

In [117]:
ar1 * ar3

array([[1, 4, 9],
       [4, 4, 9]])

In [40]:
arr = np.random.randint(1, 3, (6))
arr

array([1, 2, 2, 1, 1, 1])

In [47]:
arr_ = arr.reshape((2,3))
arr_, ar3

(array([[1, 2, 2],
        [1, 1, 1]]),
 array([[1, 2, 3],
        [4, 2, 3]]))

In [45]:
arr_ * ar3

array([[1, 4, 6],
       [4, 2, 3]])

In [48]:
arr_ / ar3

array([[1.        , 1.        , 0.66666667],
       [0.25      , 0.5       , 0.33333333]])

In [49]:
#floor division -> removes the decimals (rounds down)
arr_ // ar3

array([[1, 1, 0],
       [0, 0, 0]], dtype=int32)

In [52]:
#to the power 
arr_ ** 2

array([[1, 4, 4],
       [1, 1, 1]], dtype=int32)

In [53]:
np.square(arr_)

array([[1, 4, 4],
       [1, 1, 1]], dtype=int32)

In [55]:
arr_ % 2

array([[1, 0, 0],
       [1, 1, 1]], dtype=int32)